# Generated by Django 3.1.2 on 2021-06-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enroll', '0002_remove_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
